### ISSUE TITLE
Change the package name.

### ISSUE THREAD

**Issue by Ghost-chu** [Bilicraft-Community/StargateDynmap#5]
I nolonger actively maintain the domain `mcsunnyside.com` and I am going to stop renewing this domain.

Since I didn't actively maintain this plugin for a long time. I think it's time to find a better package for SG-Dynmap.

**Comment by Pheotis** [comment]
From the looks of it, sgdm uses com.bilicraft ; do you have similar plans for that domain?

**Comment by Ghost-chu** [comment]
> From the looks of it, sgdm uses com.bilicraft ; do you have similar plans for that domain?

I'm not belongs to Bilicraft org and Bilicraft had no plan to handle it in future so.

**Comment by Thorinwasher** [comment]
closed with https://github.com/stargate-rewritten/SG-Dynmap/commit/dd8a93e6eacce944fee420e865c428cad39e28d3
