### ISSUE TITLE
A stack trace is printed when no mapper plugin is found.

### ISSUE THREAD

**Issue by Pheotis** [Bilicraft-Community/StargateDynmap#9]
https://pastes.dev/wHADo0mCin

This should probably just be an error message followed by a graceful shutdown; no need for a stack trace to be printed.

**Comment by Thorinwasher** [comment]
Meh, let's just print a stacktrace. If a sysadmin can not read a stacktrace, then that's their fault.

This message is pretty descriptive already in the stacktrace.
